### ISSUE TITLE
Support for multiple layers

### ISSUE THREAD

**Issue by keithj2780** [anoram/leaflet-svelte#1]
Consider changing tileLayer to an array.
My requirement has a multiples layers from different sources, each with different opacities.
I'd also like to add & remove layers based on UI interaction... and the Map Component to react to those changes in the options.

**Comment by peopledrivemecrazy** [comment]
Can you give me an example? Yes, the map component isn't reactive yet I am working on it.

**Comment by keithj2780** [comment]
```
    leaflet.tileLayer('https://a.tile.openstreetmap.org/{z}/{x}/{y}.png ', {
        attribution:  'xxx',
        maxZoom:      22,
        minZoom:      5,
        opacity: 1.0
      }).addTo(map);

      googleStreetLayer = leaflet.tileLayer('//{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}',{
        maxZoom: 36,
        subdomains:['mt0','mt1','mt2','mt3'],
        attribution:  'yyy',
        minZoom:      5,
        opacity: 0.0
      });
      googleStreetLayer.addTo(map);

      googleImageryLayer = leaflet.tileLayer('//{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',{
        maxZoom: 36,
        subdomains:['mt0','mt1','mt2','mt3'],
        attribution:  'zzz',
        minZoom:      5,
        opacity: 0.0
      });
      googleImageryLayer.addTo(map);
```
Reactivity would be great 👍

**Comment by peopledrivemecrazy** [comment]
I might have a working example but not ready yet. 
![image](https://user-images.githubusercontent.com/3922469/93427277-2fb2e180-f8db-11ea-864c-10547c196905.png)

Thanks for your suggestion, I will investigate this further and add this by tonight or tomorrow.

**Comment by peopledrivemecrazy** [comment]
@keithj2780 This will introduce a breaking change on current `tileLayer` not being an array I require more time on this and add it along with reactivity.

**Comment by peopledrivemecrazy** [comment]
@keithj2780 have a look at this check this out https://leaflet.anoram.com/examples/tilelayer
